### ISSUE TITLE
1024 x 600 touchscreen reskin 

### ISSUE THREAD

**Issue by moodkillah** [LorenzoBalducci96/custom-cdj#1]
hi! i was very happy to found your custom cdj project is always that i've been dreaming since years.

my issue is the following:
 i am using an 1024 x 600 touchscreen and my main concern was the browser showing itself when the resolution is changed at the skin.xml. 
my question is how can i "extend" the performance layout? (and maybe add extra features having more screen size.)

ill be messing with the xml files that you explained in your documentation so if i find any solution to this i will be posting asap.
![Screen Shot 2019-05-12 at 6 39 11 PM](https://user-images.githubusercontent.com/50559566/57589150-6c035000-74e5-11e9-8a93-f416e849662e.png)

Thank you.

**Comment by moodkillah** [comment]
ok i managed to extend the waveform to the point i liked it. 
next, id like to get the beatloop buttons a little more bigger, but im just making bigger the container not the buttons. (the same for the hotcues)
im messing up with the beatloop.xml with size policy and minimum size but still don't get it. 

![Screen Shot 2019-05-12 at 8 05 56 PM](https://user-images.githubusercontent.com/50559566/57590451-7297c480-74f1-11e9-9a53-57fefb664643.png)

ill update if i found solution.

**Comment by LorenzoBalducci96** [comment]
For the size of the buttons you have to adjust the values in skin.xml.
Suggestion: the size of the containers will be wrapped around the buttons size, so just changing the buttons size you will have an adjustment of the containers size.
I modified some parameters, here you are the files.
[skin1024x600.zip](https://github.com/LorenzoBalducci96/custom-cdj/files/3219884/skin1024x600.zip)

**Comment by LorenzoBalducci96** [comment]
i post the resoult:
![skin](https://user-images.githubusercontent.com/39745742/58376041-579d6980-7f61-11e9-8320-542724168cc9.PNG)

**Comment by LorenzoBalducci96** [comment]
added skin in "skins" project folder
