### ISSUE TITLE
Needs CUE buttons instead of Loops

### ISSUE THREAD

**Issue by mikekimonkey** [LorenzoBalducci96/custom-cdj#2]
Hi Lorenzo,

I am running the MIXXX on a 2.8" LCD and your custom skin work perfect! Thanks so much for the hard work and nice design of the skin!

I would like to put it into a VESTAX Handy Trax portable turntable, and need some CUE buttons instead of LOOP buttons, wondering if you could allow users to modify your skin to fit their usage?

**Comment by LorenzoBalducci96** [comment]
Hi mikekimonkey thanks a lot.
Of course you can make a pull request with te custom skin in the "skins" folder now created.

**Comment by LorenzoBalducci96** [comment]
I found an old skin that i had made and i pushed into the directory.
Maybe is what you are looking for, maybe you have a better idea...feel free to use/modify/create_new and make pull requests

**Comment by mikekimonkey** [comment]
Thanks for the reply.
I should have sent you PM instead of putting Issue here, however I couldnt find anywhere to reach you. Anyway, I'm still reading the document of the Skins section of the Mixxx and may need some help, will make pull request and see how the te custom skin works. Cheers.
