### ISSUE TITLE
Waveforms not working in your skin & small design change request

### ISSUE THREAD

**Issue by lxxrxtz** [LorenzoBalducci96/custom-cdj#5]
Hey Lorenzo!

I recently saw your video regarding your custom cdj-Project and wanted to make a similar one myself. 

First I used the [skin](https://github.com/LorenzoBalducci96/custom-cdj/blob/master/skins/default_480x320.zip) you showed in your [video](https://www.youtube.com/watch?v=iwT1U_JUzzs) until I later found the skin I was kinda originally looking for after watching your video, made by you [here](https://github.com/LorenzoBalducci96/custom-cdj/issues/3#issuecomment-582615108). [This skin](https://github.com/LorenzoBalducci96/custom-cdj/issues/3#issuecomment-582615108) is exactly what I've been looking for and fills all my needs. 

However I have this issues where with [your skin](https://github.com/LorenzoBalducci96/custom-cdj/issues/3#issuecomment-582615108) applied the waveforms won't show/load on my two Raspberry Pi 3B+'ses running Mixxx 2.2.0. 
Is there a way to get them working? 
Because I tried other skins that don't fit my 3.5 inch screen, however the waveforms in these skins loaded fine, where in yours, its not the case. 
Any idea why?

Also, I wanted to ask you if you could tell me how to or if you can make a design change to this skins, where you change it from [what it looks like atm](https://github.com/LorenzoBalducci96/custom-cdj/issues/3#issuecomment-582615108) to [this](https://github.com/LorenzoBalducci96/custom-cdj/issues/3#issuecomment-582543059) because I would get a better overview from it.

Hope you're reading this and can provide me with solutions to my "problems" soon.

Kind regards, 
Lauritz ;)

**Comment by LorenzoBalducci96** [comment]
I tryied just now both skins on my raspberry pi 3b+ with mixxx 2.1.8 and mixxx 2.3.0 and are working.
Can you verify on settings->preferences->waveforms that you are using "RGB" setting for both waveform type and overview waveform?

**Comment by lxxrxtz** [comment]
I will check

**Comment by lxxrxtz** [comment]
Give me 2 minutes

**Comment by lxxrxtz** [comment]
Ok, I checked. I had them on RGB (GSLS) for some Reason, that's why it wasn't working. 

So that's fixed.

Could you do something about the design change for me too?

**Comment by LorenzoBalducci96** [comment]
if you open the two_decks_waveforms.xml there is the structure of the layout you want to change.
There are two widget groups one with vertical layout in which you can find the two templates for the performance waveforms and another widget with horizontal layout with the two templates for the overview waveform.
Simply get rid of the second widget group and put the templates in the first in the order that you want.
In any case i will upload the skin in minutes.

**Comment by lxxrxtz** [comment]
THANK YOU!
I‘ll Test the Skin tomorrow, so leave this thread open until then please, because I can then contact you in the event of something not working. If everything works, I’ll close the tomorrow by myself.

Thanks for you work! :)

**Comment by LorenzoBalducci96** [comment]
[two_decks_vertical_layout.zip](https://github.com/LorenzoBalducci96/custom-cdj/files/4921336/two_decks_vertical_layout.zip)

**Comment by lxxrxtz** [comment]
After almost 3 hours of testing it I can say that everything works fine now. 
Thanks again for your help ;)
